# Generated by Django 5.0.6 on 2024-07-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField()),
                ('nptel_status', models.BooleanField()),
                ('mobile_no', models.CharField()),
                ('branch', models.CharField()),
                ('section', models.CharField()),
            ],
        ),
    ]
